cities:
  - name: london
    country: "United Kingdom"
    listings_gz: "http://insideairbnb.com/documents/gb/london/2026-03-15/data/listings.csv.gz"
    listings_csv: "http://insideairbnb.com/documents/gb/london/2026-03-15/visualisations/listings.csv"
    calendar_gz: "http://insideairbnb.com/documents/gb/london/2026-03-15/data/calendar.csv.gz"
    reviews_gz: "http://insideairbnb.com/documents/gb/london/2026-03-15/data/reviews.csv.gz"
    reviews_csv: "http://insideairbnb.com/documents/gb/london/2026-03-15/visualisations/reviews.csv"
    neighbourhoods_csv: "http://insideairbnb.com/documents/gb/london/2026-03-15/visualisations/neighbourhoods.csv"
    neighbourhoods_geojson: "http://insideairbnb.com/documents/gb/london/2026-03-15/visualisations/neighbourhoods.geojson"

  - name: madrid
    country: "Spain"
    listings_gz: "http://insideairbnb.com/documents/es/madrid/2026-03-15/data/listings.csv.gz"
    listings_csv: "http://insideairbnb.com/documents/es/madrid/2026-03-15/visualisations/listings.csv"
    calendar_gz: "http://insideairbnb.com/documents/es/madrid/2026-03-15/data/calendar.csv.gz"
    reviews_gz: "http://insideairbnb.com/documents/es/madrid/2026-03-15/data/reviews.csv.gz"
    reviews_csv: "http://insideairbnb.com/documents/es/madrid/2026-03-15/visualisations/reviews.csv"
    neighbourhoods_csv: "http://insideairbnb.com/documents/es/madrid/2026-03-15/visualisations/neighbourhoods.csv"
    neighbourhoods_geojson: "http://insideairbnb.com/documents/es/madrid/2026-03-15/visualisations/neighbourhoods.geojson"

  - name: rome
    country: "Italy"
    listings_gz: "http://insideairbnb.com/documents/it/rome/2026-03-15/data/listings.csv.gz"
    listings_csv: "http://insideairbnb.com/documents/it/rome/2026-03-15/visualisations/listings.csv"
    calendar_gz: "http://insideairbnb.com/documents/it/rome/2026-03-15/data/calendar.csv.gz"
    reviews_gz: "http://insideairbnb.com/documents/it/rome/2026-03-15/data/reviews.csv.gz"
    reviews_csv: "http://insideairbnb.com/documents/it/rome/2026-03-15/visualisations/reviews.csv"
    neighbourhoods_csv: "http://insideairbnb.com/documents/it/rome/2026-03-15/visualisations/neighbourhoods.csv"
    neighbourhoods_geojson: "http://insideairbnb.com/documents/it/rome/2026-03-15/visualisations/neighbourhoods.geojson"

  - name: brussels
    country: "Belgium"
    listings_gz: "http://insideairbnb.com/documents/be/brussels/2026-03-15/data/listings.csv.gz"
    listings_csv: "http://insideairbnb.com/documents/be/brussels/2026-03-15/visualisations/listings.csv"
    calendar_gz: "http://insideairbnb.com/documents/be/brussels/2026-03-15/data/calendar.csv.gz"
    reviews_gz: "http://insideairbnb.com/documents/be/brussels/2026-03-15/data/reviews.csv.gz"
    reviews_csv: "http://insideairbnb.com/documents/be/brussels/2026-03-15/visualisations/reviews.csv"
    neighbourhoods_csv: "http://insideairbnb.com/documents/be/brussels/2026-03-15/visualisations/neighbourhoods.csv"
    neighbourhoods_geojson: "http://insideairbnb.com/documents/be/brussels/2026-03-15/visualisations/neighbourhoods.geojson"

  - name: berlin
    country: "Germany"
    listings_gz: "http://insideairbnb.com/documents/de/berlin/2026-03-15/data/listings.csv.gz"
    listings_csv: "http://insideairbnb.com/documents/de/berlin/2026-03-15/visualisations/listings.csv"
    calendar_gz: "http://insideairbnb.com/documents/de/berlin/2026-03-15/data/calendar.csv.gz"
    reviews_gz: "http://insideairbnb.com/documents/de/berlin/2026-03-15/data/reviews.csv.gz"
    reviews_csv: "http://insideairbnb.com/documents/de/berlin/2026-03-15/visualisations/reviews.csv"
    neighbourhoods_csv: "http://insideairbnb.com/documents/de/berlin/2026-03-15/visualisations/neighbourhoods.csv"
    neighbourhoods_geojson: "http://insideairbnb.com/documents/de/berlin/2026-03-15/visualisations/neighbourhoods.geojson"

  - name: amsterdam
    country: "Netherlands"
    listings_gz: "http://insideairbnb.com/documents/nl/amsterdam/2026-03-15/data/listings.csv.gz"
    listings_csv: "http://insideairbnb.com/documents/nl/amsterdam/2026-03-15/visualisations/listings.csv"
    calendar_gz: "http://insideairbnb.com/documents/nl/amsterdam/2026-03-15/data/calendar.csv.gz"
    reviews_gz: "http://insideairbnb.com/documents/nl/amsterdam/2026-03-15/data/reviews.csv.gz"
    reviews_csv: "http://insideairbnb.com/documents/nl/amsterdam/2026-03-15/visualisations/reviews.csv"
    neighbourhoods_csv: "http://insideairbnb.com/documents/nl/amsterdam/2026-03-15/visualisations/neighbourhoods.csv"
    neighbourhoods_geojson: "http://insideairbnb.com/documents/nl/amsterdam/2026-03-15/visualisations/neighbourhoods.geojson"

  - name: vienna
    country: "Austria"
    listings_gz: "http://insideairbnb.com/documents/at/vienna/2026-03-15/data/listings.csv.gz"
    listings_csv: "http://insideairbnb.com/documents/at/vienna/2026-03-15/visualisations/listings.csv"
    calendar_gz: "http://insideairbnb.com/documents/at/vienna/2026-03-15/data/calendar.csv.gz"
    reviews_gz: "http://insideairbnb.com/documents/at/vienna/2026-03-15/data/reviews.csv.gz"
    reviews_csv: "http://insideairbnb.com/documents/at/vienna/2026-03-15/visualisations/reviews.csv"
    neighbourhoods_csv: "http://insideairbnb.com/documents/at/vienna/2026-03-15/visualisations/neighbourhoods.csv"
    neighbourhoods_geojson: "http://insideairbnb.com/documents/at/vienna/2026-03-15/visualisations/neighbourhoods.geojson"

enabled_cities:
  - london
  - madrid
  - rome
  - brussels
  - berlin
  - amsterdam
  - vienna